// Code generated by qtc from "node.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/admin/node.qtpl:1
package admin

//line views/admin/node.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/admin/node.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/admin/node.qtpl:1
func (p *Node) StreamMainBody(qw422016 *qt422016.Writer) {
//line views/admin/node.qtpl:1
	qw422016.N().S(`
<div class="index">
    <div class="markdown-body entry-content">
    <h1>`)
//line views/admin/node.qtpl:4
	qw422016.E().S(p.Title)
//line views/admin/node.qtpl:4
	qw422016.N().S(`</h1>

    <form action="" method="post" class="pure-form pure-form-stacked">
        <fieldset>
            <legend>`)
//line views/admin/node.qtpl:8
	qw422016.E().S(p.Act)
//line views/admin/node.qtpl:8
	qw422016.N().S(` 节点</legend>

            <p>Score: 显示排序，大排前</p>

            <div class="pure-g">
                <div class="pure-u-1 pure-u-sm-1-6">
                    <label for="Name">Name</label>
                    <input id="Name" name="Name" class="pure-u-23-24" type="text" value="`)
//line views/admin/node.qtpl:15
	qw422016.E().S(p.Node.Name)
//line views/admin/node.qtpl:15
	qw422016.N().S(`" required>
                </div>

                <div class="pure-u-1 pure-u-sm-1-6">
                    <label for="Score">Score</label>
                    <input id="Score" name="Score" class="pure-u-23-24" type="number" value="`)
//line views/admin/node.qtpl:20
	qw422016.N().D(p.Node.Score)
//line views/admin/node.qtpl:20
	qw422016.N().S(`" required>
                </div>

            </div>

            <div class="pure-g">
                <div class="pure-u-1 pure-u-sm-1-1">
                    <label for="About">About</label>
                    <textarea id="About" name="About" class="pure-input-1">`)
//line views/admin/node.qtpl:28
	qw422016.E().S(p.Node.About)
//line views/admin/node.qtpl:28
	qw422016.N().S(`</textarea>
                </div>
            </div>


            <button type="submit" class="pure-button pure-button-primary">提交</button>
        </fieldset>
    </form>

    <h2>节点列表</h2>

    <table class="pure-table">
        <thead>
            <tr>
                <th>#ID</th>
                <th>Name</th>
                <th>Score</th>
                <th>About</th>
            </tr>
        </thead>
        <tbody>
            `)
//line views/admin/node.qtpl:49
	for i, v := range p.NodeLst {
//line views/admin/node.qtpl:49
		qw422016.N().S(`
            <tr `)
//line views/admin/node.qtpl:50
		if i%2 == 0 {
//line views/admin/node.qtpl:50
			qw422016.N().S(`class="pure-table-odd"`)
//line views/admin/node.qtpl:50
		}
//line views/admin/node.qtpl:50
		qw422016.N().S(`>
                <td>`)
//line views/admin/node.qtpl:51
		qw422016.N().DUL(v.ID)
//line views/admin/node.qtpl:51
		qw422016.N().S(`</td>
                <td><a href="/admin/node?id=`)
//line views/admin/node.qtpl:52
		qw422016.N().DUL(v.ID)
//line views/admin/node.qtpl:52
		qw422016.N().S(`">`)
//line views/admin/node.qtpl:52
		qw422016.E().S(v.Name)
//line views/admin/node.qtpl:52
		qw422016.N().S(`</a></td>
                <td>`)
//line views/admin/node.qtpl:53
		qw422016.N().D(v.Score)
//line views/admin/node.qtpl:53
		qw422016.N().S(`</td>
                <td>`)
//line views/admin/node.qtpl:54
		qw422016.E().S(v.About)
//line views/admin/node.qtpl:54
		qw422016.N().S(`</td>
            </tr>
            `)
//line views/admin/node.qtpl:56
	}
//line views/admin/node.qtpl:56
	qw422016.N().S(`
        </tbody>
    </table>

    </div>
</div>

`)
//line views/admin/node.qtpl:63
}

//line views/admin/node.qtpl:63
func (p *Node) WriteMainBody(qq422016 qtio422016.Writer) {
//line views/admin/node.qtpl:63
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/admin/node.qtpl:63
	p.StreamMainBody(qw422016)
//line views/admin/node.qtpl:63
	qt422016.ReleaseWriter(qw422016)
//line views/admin/node.qtpl:63
}

//line views/admin/node.qtpl:63
func (p *Node) MainBody() string {
//line views/admin/node.qtpl:63
	qb422016 := qt422016.AcquireByteBuffer()
//line views/admin/node.qtpl:63
	p.WriteMainBody(qb422016)
//line views/admin/node.qtpl:63
	qs422016 := string(qb422016.B)
//line views/admin/node.qtpl:63
	qt422016.ReleaseByteBuffer(qb422016)
//line views/admin/node.qtpl:63
	return qs422016
//line views/admin/node.qtpl:63
}
