// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// This is a base page template. All the other template pages implement this interface.
//

//line views/ybs/base.qtpl:3
package ybs

//line views/ybs/base.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/ybs/base.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/ybs/base.qtpl:4
type Page interface {
//line views/ybs/base.qtpl:4
	Header() string
//line views/ybs/base.qtpl:4
	StreamHeader(qw422016 *qt422016.Writer)
//line views/ybs/base.qtpl:4
	WriteHeader(qq422016 qtio422016.Writer)
//line views/ybs/base.qtpl:4
	Banner() string
//line views/ybs/base.qtpl:4
	StreamBanner(qw422016 *qt422016.Writer)
//line views/ybs/base.qtpl:4
	WriteBanner(qq422016 qtio422016.Writer)
//line views/ybs/base.qtpl:4
	MainBodyNav() string
//line views/ybs/base.qtpl:4
	StreamMainBodyNav(qw422016 *qt422016.Writer)
//line views/ybs/base.qtpl:4
	WriteMainBodyNav(qq422016 qtio422016.Writer)
//line views/ybs/base.qtpl:4
	MainBody() string
//line views/ybs/base.qtpl:4
	StreamMainBody(qw422016 *qt422016.Writer)
//line views/ybs/base.qtpl:4
	WriteMainBody(qq422016 qtio422016.Writer)
//line views/ybs/base.qtpl:4
	Aside() string
//line views/ybs/base.qtpl:4
	StreamAside(qw422016 *qt422016.Writer)
//line views/ybs/base.qtpl:4
	WriteAside(qq422016 qtio422016.Writer)
//line views/ybs/base.qtpl:4
	Footer() string
//line views/ybs/base.qtpl:4
	StreamFooter(qw422016 *qt422016.Writer)
//line views/ybs/base.qtpl:4
	WriteFooter(qq422016 qtio422016.Writer)
//line views/ybs/base.qtpl:4
}

// Page prints a page implementing Page interface.

//line views/ybs/base.qtpl:15
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line views/ybs/base.qtpl:15
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <meta charset="utf-8">
    `)
//line views/ybs/base.qtpl:20
	p.StreamHeader(qw422016)
//line views/ybs/base.qtpl:20
	qw422016.N().S(`
    <meta name="HandheldFriendly" content="True">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1" />
    <meta content="yes" name="apple-mobile-web-app-capable" />
    <meta content="black" name="apple-mobile-web-app-status-bar-style" />
    <meta name="format-detection" content="telephone=no" />
    <link rel="shortcut icon" href="/static/favicon.png" type="image/x-icon" />
    <link rel="top" title="Back to Top" href="#" />
    <!--[if lte IE 8]>
    <link rel="stylesheet" href="/static/css/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="/static/css/grids-responsive-min.css">
    <!--<![endif]-->
</head>

<body>
<a name="top"></a>
<header role="banner" class="header-wrap">
    <div class="home-menu pure-menu pure-menu-horizontal">
        `)
//line views/ybs/base.qtpl:40
	p.StreamBanner(qw422016)
//line views/ybs/base.qtpl:40
	qw422016.N().S(`
    </div>
</header>

<div id="main" class="main-wrap">
    <div id="content" class="pure-g">
        <div class="pure-u-1 pure-u-sm-17-24">
            <div class="main-left-body">

                `)
//line views/ybs/base.qtpl:49
	p.StreamMainBodyNav(qw422016)
//line views/ybs/base.qtpl:49
	qw422016.N().S(`

                `)
//line views/ybs/base.qtpl:51
	p.StreamMainBody(qw422016)
//line views/ybs/base.qtpl:51
	qw422016.N().S(`

            </div>
        </div>
        <div class="pure-u-1 pure-u-sm-7-24">
            <div class="main-right-body">
                `)
//line views/ybs/base.qtpl:57
	p.StreamAside(qw422016)
//line views/ybs/base.qtpl:57
	qw422016.N().S(`
            </div>
        </div>
    </div>
</div>

<footer role="contentinfo">
    `)
//line views/ybs/base.qtpl:64
	p.StreamFooter(qw422016)
//line views/ybs/base.qtpl:64
	qw422016.N().S(`
</footer>
<a style="display: none; " rel="nofollow" href="#top" id="go-to-top">▲</a>
<script>
document.addEventListener("scroll", handleScroll);
let scrollToTopBtn = document.getElementById("go-to-top");
scrollToTopBtn.addEventListener("click", scrollToTop);

function handleScroll() {
    if (document.documentElement.scrollTop > 300) {
        scrollToTopBtn.style.display = "block";
    } else if (document.documentElement.scrollTop < 300){
        scrollToTopBtn.style.display = "none";
    }
}
</script>
</body>
</html>
`)
//line views/ybs/base.qtpl:82
}

//line views/ybs/base.qtpl:82
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line views/ybs/base.qtpl:82
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/base.qtpl:82
	StreamPageTemplate(qw422016, p)
//line views/ybs/base.qtpl:82
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/base.qtpl:82
}

//line views/ybs/base.qtpl:82
func PageTemplate(p Page) string {
//line views/ybs/base.qtpl:82
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/base.qtpl:82
	WritePageTemplate(qb422016, p)
//line views/ybs/base.qtpl:82
	qs422016 := string(qb422016.B)
//line views/ybs/base.qtpl:82
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/base.qtpl:82
	return qs422016
//line views/ybs/base.qtpl:82
}

// Header bg

//line views/ybs/base.qtpl:86
func (p *BasePage) StreamHeader(qw422016 *qt422016.Writer) {
//line views/ybs/base.qtpl:86
	qw422016.N().S(`
<title>`)
//line views/ybs/base.qtpl:87
	qw422016.E().S(p.Title)
//line views/ybs/base.qtpl:87
	qw422016.N().S(`</title>
<meta name="description" content="`)
//line views/ybs/base.qtpl:88
	qw422016.E().S(p.Description)
//line views/ybs/base.qtpl:88
	qw422016.N().S(`">
<meta name="keywords" content="`)
//line views/ybs/base.qtpl:89
	qw422016.E().S(p.Keywords)
//line views/ybs/base.qtpl:89
	qw422016.N().S(`">
<link rel="canonical" href="`)
//line views/ybs/base.qtpl:90
	qw422016.E().S(p.Canonical)
//line views/ybs/base.qtpl:90
	qw422016.N().S(`">
<link href="/feed" rel="alternate" title="`)
//line views/ybs/base.qtpl:91
	qw422016.E().S(p.SiteCf.Name)
//line views/ybs/base.qtpl:91
	qw422016.N().S(`" type="application/atom+xml">
<link rel="stylesheet" href="/static/css/main.css?v=`)
//line views/ybs/base.qtpl:92
	qw422016.E().S(p.SiteCf.SelfHash)
//line views/ybs/base.qtpl:92
	qw422016.N().S(`" type="text/css">
<script src="/static/js/main.js?v=`)
//line views/ybs/base.qtpl:93
	qw422016.E().S(p.SiteCf.SelfHash)
//line views/ybs/base.qtpl:93
	qw422016.N().S(`"></script>

`)
//line views/ybs/base.qtpl:95
	if len(p.JsonLd) > 0 {
//line views/ybs/base.qtpl:95
		qw422016.N().S(`
<script type="application/ld+json">
`)
//line views/ybs/base.qtpl:97
		qw422016.N().S(p.JsonLd)
//line views/ybs/base.qtpl:97
		qw422016.N().S(`
</script>
`)
//line views/ybs/base.qtpl:99
	}
//line views/ybs/base.qtpl:99
	qw422016.N().S(`

`)
//line views/ybs/base.qtpl:101
	if p.ShowAutoAd && len(p.SiteCf.GoogleAutoAdJs) > 0 {
//line views/ybs/base.qtpl:101
		qw422016.N().S(`
`)
//line views/ybs/base.qtpl:102
		qw422016.N().S(p.SiteCf.GoogleAutoAdJs)
//line views/ybs/base.qtpl:102
		qw422016.N().S(`
`)
//line views/ybs/base.qtpl:103
	}
//line views/ybs/base.qtpl:103
	qw422016.N().S(`

`)
//line views/ybs/base.qtpl:105
	if len(p.SiteCf.HeaderPartCon) > 0 {
//line views/ybs/base.qtpl:105
		qw422016.N().S(`
`)
//line views/ybs/base.qtpl:106
		qw422016.N().S(p.SiteCf.HeaderPartCon)
//line views/ybs/base.qtpl:106
		qw422016.N().S(`
`)
//line views/ybs/base.qtpl:107
	}
//line views/ybs/base.qtpl:107
	qw422016.N().S(`

`)
//line views/ybs/base.qtpl:109
}

//line views/ybs/base.qtpl:109
func (p *BasePage) WriteHeader(qq422016 qtio422016.Writer) {
//line views/ybs/base.qtpl:109
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/base.qtpl:109
	p.StreamHeader(qw422016)
//line views/ybs/base.qtpl:109
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/base.qtpl:109
}

//line views/ybs/base.qtpl:109
func (p *BasePage) Header() string {
//line views/ybs/base.qtpl:109
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/base.qtpl:109
	p.WriteHeader(qb422016)
//line views/ybs/base.qtpl:109
	qs422016 := string(qb422016.B)
//line views/ybs/base.qtpl:109
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/base.qtpl:109
	return qs422016
//line views/ybs/base.qtpl:109
}

// Header ed
//
// Banner bg

//line views/ybs/base.qtpl:113
func (p *BasePage) StreamBanner(qw422016 *qt422016.Writer) {
//line views/ybs/base.qtpl:113
	qw422016.N().S(`
<a href="/" class="pure-menu-heading pure-menu-link">`)
//line views/ybs/base.qtpl:114
	qw422016.E().S(p.SiteCf.Name)
//line views/ybs/base.qtpl:114
	qw422016.N().S(`</a>
<ul class="pure-menu-list">
    `)
//line views/ybs/base.qtpl:116
	if p.CurrentUser.ID > 0 {
//line views/ybs/base.qtpl:116
		qw422016.N().S(`
    <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
        <a href="#" id="menuLink1" class="pure-menu-link" style="padding: .5em 1em;"><img class="avatar" src="/static/avatar/`)
//line views/ybs/base.qtpl:118
		qw422016.N().DUL(p.CurrentUser.ID)
//line views/ybs/base.qtpl:118
		qw422016.N().S(`.jpg" alt="`)
//line views/ybs/base.qtpl:118
		qw422016.E().S(p.CurrentUser.Name)
//line views/ybs/base.qtpl:118
		qw422016.N().S(` avatar"/></a>
        <ul class="pure-menu-children">
            <li class="pure-menu-item"><a href="/setting" class="pure-menu-link">设置</a></li>
            <li class="pure-menu-item"><a href="/logout" class="pure-menu-link menu-item-divided">退出</a></li>
        </ul>
    </li>
    `)
//line views/ybs/base.qtpl:124
	} else {
//line views/ybs/base.qtpl:124
		qw422016.N().S(`
    <li class="pure-menu-item"><a href="/login" rel="nofollow" class="pure-menu-link">登录</a></li>
    <li class="pure-menu-item"><a href="/register" rel="nofollow" class="pure-menu-link">注册</a></li>
    `)
//line views/ybs/base.qtpl:127
	}
//line views/ybs/base.qtpl:127
	qw422016.N().S(`
</ul>
`)
//line views/ybs/base.qtpl:129
}

//line views/ybs/base.qtpl:129
func (p *BasePage) WriteBanner(qq422016 qtio422016.Writer) {
//line views/ybs/base.qtpl:129
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/base.qtpl:129
	p.StreamBanner(qw422016)
//line views/ybs/base.qtpl:129
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/base.qtpl:129
}

//line views/ybs/base.qtpl:129
func (p *BasePage) Banner() string {
//line views/ybs/base.qtpl:129
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/base.qtpl:129
	p.WriteBanner(qb422016)
//line views/ybs/base.qtpl:129
	qs422016 := string(qb422016.B)
//line views/ybs/base.qtpl:129
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/base.qtpl:129
	return qs422016
//line views/ybs/base.qtpl:129
}

// Banner ed
//
// MainBodyNav bg

//line views/ybs/base.qtpl:133
func (p *BasePage) StreamMainBodyNav(qw422016 *qt422016.Writer) {
//line views/ybs/base.qtpl:133
	qw422016.N().S(`
`)
//line views/ybs/base.qtpl:134
	if p.CurrentUser.ID > 0 {
//line views/ybs/base.qtpl:134
		qw422016.N().S(`
<div class="body-nav box bot-line">
    <div class="pure-button-group">
        `)
//line views/ybs/base.qtpl:137
		if p.CurrentUser.Flag == 0 {
//line views/ybs/base.qtpl:137
			qw422016.N().S(`
        <span class="pure-button button-warning">您已被管理员禁用</span>
        `)
//line views/ybs/base.qtpl:139
		} else {
//line views/ybs/base.qtpl:139
			qw422016.N().S(`
        `)
//line views/ybs/base.qtpl:140
			if p.CurrentUser.Flag == 1 {
//line views/ybs/base.qtpl:140
				qw422016.N().S(`
        <span class="pure-button button-warning">请等待管理员审核</span>
        `)
//line views/ybs/base.qtpl:142
			}
//line views/ybs/base.qtpl:142
			qw422016.N().S(`
        `)
//line views/ybs/base.qtpl:143
			if p.CurrentUser.Flag >= 5 {
//line views/ybs/base.qtpl:143
				qw422016.N().S(`
        `)
//line views/ybs/base.qtpl:144
				if p.HasMsg {
//line views/ybs/base.qtpl:144
					qw422016.N().S(`
        <a class="pure-button button-warning" href="/my/msg">未读信息</a>
        `)
//line views/ybs/base.qtpl:146
				}
//line views/ybs/base.qtpl:146
				qw422016.N().S(`
        <a class="pure-button pure-button-primary" href="/topic/add?nid=`)
//line views/ybs/base.qtpl:147
				qw422016.N().DUL(p.DefaultNode.ID)
//line views/ybs/base.qtpl:147
				qw422016.N().S(`">发帖</a>
        `)
//line views/ybs/base.qtpl:148
			}
//line views/ybs/base.qtpl:148
			qw422016.N().S(`
        `)
//line views/ybs/base.qtpl:149
			if p.CurrentUser.Flag >= 99 {
//line views/ybs/base.qtpl:149
				qw422016.N().S(`
            `)
//line views/ybs/base.qtpl:150
				if p.HasTopicReview {
//line views/ybs/base.qtpl:150
					qw422016.N().S(`
            <a class="pure-button button-warning" href="/admin/topic/review">审帖</a>
            `)
//line views/ybs/base.qtpl:152
				}
//line views/ybs/base.qtpl:152
				qw422016.N().S(`
            `)
//line views/ybs/base.qtpl:153
				if p.HasReplyReview {
//line views/ybs/base.qtpl:153
					qw422016.N().S(`
            <a class="pure-button button-warning" href="/admin/comment/review">审评</a>
            `)
//line views/ybs/base.qtpl:155
				}
//line views/ybs/base.qtpl:155
				qw422016.N().S(`
            <a class="pure-button" href="/admin/node">节点</a>
            <a class="pure-button" href="/admin/user">用户</a>
            <a class="pure-button" href="/admin/link">链接</a>
            <a class="pure-button" href="/admin/site/conf">设置</a>
        `)
//line views/ybs/base.qtpl:160
			}
//line views/ybs/base.qtpl:160
			qw422016.N().S(`
        `)
//line views/ybs/base.qtpl:161
		}
//line views/ybs/base.qtpl:161
		qw422016.N().S(`
    </div>
</div>
`)
//line views/ybs/base.qtpl:164
	}
//line views/ybs/base.qtpl:164
	qw422016.N().S(`
`)
//line views/ybs/base.qtpl:165
}

//line views/ybs/base.qtpl:165
func (p *BasePage) WriteMainBodyNav(qq422016 qtio422016.Writer) {
//line views/ybs/base.qtpl:165
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/base.qtpl:165
	p.StreamMainBodyNav(qw422016)
//line views/ybs/base.qtpl:165
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/base.qtpl:165
}

//line views/ybs/base.qtpl:165
func (p *BasePage) MainBodyNav() string {
//line views/ybs/base.qtpl:165
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/base.qtpl:165
	p.WriteMainBodyNav(qb422016)
//line views/ybs/base.qtpl:165
	qs422016 := string(qb422016.B)
//line views/ybs/base.qtpl:165
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/base.qtpl:165
	return qs422016
//line views/ybs/base.qtpl:165
}

// MainBodyNav ed
//
// MainBody bg

//line views/ybs/base.qtpl:169
func (p *BasePage) StreamMainBody(qw422016 *qt422016.Writer) {
//line views/ybs/base.qtpl:169
	qw422016.N().S(`
This is a base MainBody
`)
//line views/ybs/base.qtpl:171
}

//line views/ybs/base.qtpl:171
func (p *BasePage) WriteMainBody(qq422016 qtio422016.Writer) {
//line views/ybs/base.qtpl:171
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/base.qtpl:171
	p.StreamMainBody(qw422016)
//line views/ybs/base.qtpl:171
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/base.qtpl:171
}

//line views/ybs/base.qtpl:171
func (p *BasePage) MainBody() string {
//line views/ybs/base.qtpl:171
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/base.qtpl:171
	p.WriteMainBody(qb422016)
//line views/ybs/base.qtpl:171
	qs422016 := string(qb422016.B)
//line views/ybs/base.qtpl:171
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/base.qtpl:171
	return qs422016
//line views/ybs/base.qtpl:171
}

// MainBody ed
//
// Aside bg

//line views/ybs/base.qtpl:175
func (p *BasePage) StreamAside(qw422016 *qt422016.Writer) {
//line views/ybs/base.qtpl:175
	qw422016.N().S(`
<aside class="sidebar">

    <section class="search-form">
        <form action="/q" method="get" class="pure-form">
            <input type="text" name="q" class="pure-input-rounded" placeholder="站内搜索" autocomplete="off" />
        </form>
    </section>

    `)
//line views/ybs/base.qtpl:184
	if len(p.RecentComment) > 0 {
//line views/ybs/base.qtpl:184
		qw422016.N().S(`
    <section>
        <h1>💬 最近评论</h1>
        <ul id="recent_comments">
            `)
//line views/ybs/base.qtpl:188
		for k := range p.RecentComment {
//line views/ybs/base.qtpl:188
			qw422016.N().S(`
            <li>
                <img alt="`)
//line views/ybs/base.qtpl:190
			qw422016.E().S(p.RecentComment[k].Name)
//line views/ybs/base.qtpl:190
			qw422016.N().S(` avatar" src="/static/avatar/`)
//line views/ybs/base.qtpl:190
			qw422016.N().DUL(p.RecentComment[k].UserId)
//line views/ybs/base.qtpl:190
			qw422016.N().S(`.jpg" class="avatar"> <a href="`)
//line views/ybs/base.qtpl:190
			qw422016.E().S(p.RecentComment[k].Link)
//line views/ybs/base.qtpl:190
			qw422016.N().S(`">`)
//line views/ybs/base.qtpl:190
			qw422016.E().S(p.RecentComment[k].Content)
//line views/ybs/base.qtpl:190
			qw422016.N().S(`</a>
            </li>
            `)
//line views/ybs/base.qtpl:192
		}
//line views/ybs/base.qtpl:192
		qw422016.N().S(`
        </ul>
    </section>
    `)
//line views/ybs/base.qtpl:195
	}
//line views/ybs/base.qtpl:195
	qw422016.N().S(`

    `)
//line views/ybs/base.qtpl:197
	if len(p.NodeLst) > 0 {
//line views/ybs/base.qtpl:197
		qw422016.N().S(`
    <section>
        <h1>📁 分类</h1>
        <div id="top-category-list">
            `)
//line views/ybs/base.qtpl:201
		for k := range p.NodeLst {
//line views/ybs/base.qtpl:201
			qw422016.N().S(`
            <a href="/n/`)
//line views/ybs/base.qtpl:202
			qw422016.N().DUL(p.NodeLst[k].ID)
//line views/ybs/base.qtpl:202
			qw422016.N().S(`">`)
//line views/ybs/base.qtpl:202
			qw422016.E().S(p.NodeLst[k].Name)
//line views/ybs/base.qtpl:202
			qw422016.N().S(`<span class="tag_meta">(`)
//line views/ybs/base.qtpl:202
			qw422016.N().DUL(p.NodeLst[k].TopicNum)
//line views/ybs/base.qtpl:202
			qw422016.N().S(`)</span></a>
            `)
//line views/ybs/base.qtpl:203
		}
//line views/ybs/base.qtpl:203
		qw422016.N().S(`
        </div>
    </section>
    `)
//line views/ybs/base.qtpl:206
	}
//line views/ybs/base.qtpl:206
	qw422016.N().S(`

    `)
//line views/ybs/base.qtpl:208
	if len(p.RangeTopicLst) > 0 {
//line views/ybs/base.qtpl:208
		qw422016.N().S(`
    <section>
        <h1>📝 最近浏览</h1>
        <ul id="recent_posts">
            `)
//line views/ybs/base.qtpl:212
		for k := range p.RangeTopicLst {
//line views/ybs/base.qtpl:212
			qw422016.N().S(`
            <li><a href="/t/`)
//line views/ybs/base.qtpl:213
			qw422016.N().DUL(p.RangeTopicLst[k].ID)
//line views/ybs/base.qtpl:213
			qw422016.N().S(`">`)
//line views/ybs/base.qtpl:213
			qw422016.E().S(p.RangeTopicLst[k].Title)
//line views/ybs/base.qtpl:213
			qw422016.N().S(`</a></li>
            `)
//line views/ybs/base.qtpl:214
		}
//line views/ybs/base.qtpl:214
		qw422016.N().S(`
        </ul>
    </section>
    `)
//line views/ybs/base.qtpl:217
	}
//line views/ybs/base.qtpl:217
	qw422016.N().S(`

    `)
//line views/ybs/base.qtpl:219
	if len(p.TagCloud) > 0 {
//line views/ybs/base.qtpl:219
		qw422016.N().S(`
    <section>
        <h1>🏷️ 标签</h1>
        <div id="tag-cloud">
            `)
//line views/ybs/base.qtpl:223
		for k := range p.TagCloud {
//line views/ybs/base.qtpl:223
			qw422016.N().S(`
            <a href="/tag/`)
//line views/ybs/base.qtpl:224
			qw422016.N().U(p.TagCloud[k].Name)
//line views/ybs/base.qtpl:224
			qw422016.N().S(`">`)
//line views/ybs/base.qtpl:224
			qw422016.E().S(p.TagCloud[k].Name)
//line views/ybs/base.qtpl:224
			qw422016.N().S(`<span class="tag-meta">(`)
//line views/ybs/base.qtpl:224
			qw422016.N().D(p.TagCloud[k].Size)
//line views/ybs/base.qtpl:224
			qw422016.N().S(`)</span></a>
            `)
//line views/ybs/base.qtpl:225
		}
//line views/ybs/base.qtpl:225
		qw422016.N().S(`
        </div>
    </section>
    `)
//line views/ybs/base.qtpl:228
	}
//line views/ybs/base.qtpl:228
	qw422016.N().S(`

    `)
//line views/ybs/base.qtpl:230
	if len(p.LinkLst) > 0 {
//line views/ybs/base.qtpl:230
		qw422016.N().S(`
    <section>
        <h1>🔗 链接</h1>
        <ul id="link-cloud">
            `)
//line views/ybs/base.qtpl:234
		for k := range p.LinkLst {
//line views/ybs/base.qtpl:234
			qw422016.N().S(`
            <li><a href="`)
//line views/ybs/base.qtpl:235
			qw422016.E().S(p.LinkLst[k].Url)
//line views/ybs/base.qtpl:235
			qw422016.N().S(`" target="_blank">`)
//line views/ybs/base.qtpl:235
			qw422016.E().S(p.LinkLst[k].Name)
//line views/ybs/base.qtpl:235
			qw422016.N().S(`</a></li>
            `)
//line views/ybs/base.qtpl:236
		}
//line views/ybs/base.qtpl:236
		qw422016.N().S(`
        </ul>
    </section>
    `)
//line views/ybs/base.qtpl:239
	}
//line views/ybs/base.qtpl:239
	qw422016.N().S(`

    `)
//line views/ybs/base.qtpl:241
	if p.SiteInfo.NodeNum > 0 {
//line views/ybs/base.qtpl:241
		qw422016.N().S(`
    <section>
        <h1>💡 本站已稳定运行 `)
//line views/ybs/base.qtpl:243
		qw422016.E().S(p.SiteInfo.Days)
//line views/ybs/base.qtpl:243
		qw422016.N().S(`</h1>
        <ul id="site-info">
            <li>会员: `)
//line views/ybs/base.qtpl:245
		qw422016.N().DUL(p.SiteInfo.UserNum)
//line views/ybs/base.qtpl:245
		qw422016.N().S(`</li>
            <li>帖子: `)
//line views/ybs/base.qtpl:246
		qw422016.N().DUL(p.SiteInfo.PostNum)
//line views/ybs/base.qtpl:246
		qw422016.N().S(`</li>
            <li>回复: `)
//line views/ybs/base.qtpl:247
		qw422016.N().DUL(p.SiteInfo.ReplyNum)
//line views/ybs/base.qtpl:247
		qw422016.N().S(`</li>
            <li>分类: `)
//line views/ybs/base.qtpl:248
		qw422016.N().DUL(p.SiteInfo.NodeNum)
//line views/ybs/base.qtpl:248
		qw422016.N().S(`</li>
            <li>标签: `)
//line views/ybs/base.qtpl:249
		qw422016.N().DUL(p.SiteInfo.TagNum)
//line views/ybs/base.qtpl:249
		qw422016.N().S(`</li>
            <li>`)
//line views/ybs/base.qtpl:250
		qw422016.E().S(p.SiteInfo.WeekNum)
//line views/ybs/base.qtpl:250
		qw422016.N().S(`</li>
        </ul>
    </section>
    `)
//line views/ybs/base.qtpl:253
	}
//line views/ybs/base.qtpl:253
	qw422016.N().S(`

</aside>

`)
//line views/ybs/base.qtpl:257
}

//line views/ybs/base.qtpl:257
func (p *BasePage) WriteAside(qq422016 qtio422016.Writer) {
//line views/ybs/base.qtpl:257
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/base.qtpl:257
	p.StreamAside(qw422016)
//line views/ybs/base.qtpl:257
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/base.qtpl:257
}

//line views/ybs/base.qtpl:257
func (p *BasePage) Aside() string {
//line views/ybs/base.qtpl:257
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/base.qtpl:257
	p.WriteAside(qb422016)
//line views/ybs/base.qtpl:257
	qs422016 := string(qb422016.B)
//line views/ybs/base.qtpl:257
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/base.qtpl:257
	return qs422016
//line views/ybs/base.qtpl:257
}

// Aside ed
//
// Footer bg

//line views/ybs/base.qtpl:261
func (p *BasePage) StreamFooter(qw422016 *qt422016.Writer) {
//line views/ybs/base.qtpl:261
	qw422016.N().S(`
<p>
    Copyright &copy; <a href="/">`)
//line views/ybs/base.qtpl:263
	qw422016.E().S(p.SiteCf.Name)
//line views/ybs/base.qtpl:263
	qw422016.N().S(`</a> -
    <span class="credit">Powered by <a href="https://youbbs.org">goYouBBS</a> - <a href="#">&uarr;Go Top</a> </span>
</p>

`)
//line views/ybs/base.qtpl:267
	if len(p.SiteCf.FooterPartHtml) > 0 {
//line views/ybs/base.qtpl:267
		qw422016.N().S(`
`)
//line views/ybs/base.qtpl:268
		qw422016.N().S(p.SiteCf.FooterPartHtml)
//line views/ybs/base.qtpl:268
		qw422016.N().S(`
`)
//line views/ybs/base.qtpl:269
	}
//line views/ybs/base.qtpl:269
	qw422016.N().S(`

`)
//line views/ybs/base.qtpl:271
}

//line views/ybs/base.qtpl:271
func (p *BasePage) WriteFooter(qq422016 qtio422016.Writer) {
//line views/ybs/base.qtpl:271
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/ybs/base.qtpl:271
	p.StreamFooter(qw422016)
//line views/ybs/base.qtpl:271
	qt422016.ReleaseWriter(qw422016)
//line views/ybs/base.qtpl:271
}

//line views/ybs/base.qtpl:271
func (p *BasePage) Footer() string {
//line views/ybs/base.qtpl:271
	qb422016 := qt422016.AcquireByteBuffer()
//line views/ybs/base.qtpl:271
	p.WriteFooter(qb422016)
//line views/ybs/base.qtpl:271
	qs422016 := string(qb422016.B)
//line views/ybs/base.qtpl:271
	qt422016.ReleaseByteBuffer(qb422016)
//line views/ybs/base.qtpl:271
	return qs422016
//line views/ybs/base.qtpl:271
}

// Footer ed
